### PR TITLE
Villan31 branch

### PR DESCRIPTION
**Pull request by enigma2522**
A simple leaflet map with initial attempts at search, geocoding, data
popups, data aliasing, and retroject, converted, and merged geoJSON
using data from http://www.sangis.org/ park data shapeless.

### CODE REVIEW

**Comment by cgiovando** [comment]
Thank you @enigma2522! Let's review this tonight and try to deploy to gh-pages

**Comment by willingc** [comment]
Nice! A pull request tonight. Nicely done @enigma2522 and @cgiovando. :children_crossing:

**Comment by 47ronin** [comment]
There's some Windows-specific local paths explicitly referenced in `app/data/Active/active_use.shp.xml`

**Comment by enigma2522** [comment]
Are they giving you issues? I use dynamic pathing in my web development and haven't had any issues in the past. Has the directory structure changed? If not, what do you think they should be to work better?

**Comment by 47ronin** [comment]
@enigma2522 just to make sure… paths like `C:\Documents and Settings\kmarlow\Desktop` which are in the committed files— will those get stripped out, dynamically changed, or become otherwise a non-issue in deployment?

**Comment by enigma2522** [comment]
I misunderstood. The xml file your talking about it a shapefile which is derived from an ESRI standard. I don't have control over any paths in it and I haven't set anything in it. If you see paths in the XML just ignore them, they do not matter. With shapefiles, the only truly important files a .shp, .dbf, and .prj.

**Comment by enigma2522** [comment]
.shp is the shapefile which contains the geographic info
.dbf is the attribute data for the geographic data
.prj is the projection file with the coordinate system/datum info in it.

**Comment by enigma2522** [comment]
You had me worried for a minute. I thought I had put bad paths in code. The shapefiles are just there as reference data. The JSON files are actually what is read by the code. 

In the latest version, I am transitioning from parks areas(polygons) to park centroids(or markers) which have been consolidated and named better and I am about to begin looking at finding the nearest parks (top 10 or something) and displaying this data.I am not sure exactly how we want to show this data to the users. I am also thinking we need to display data for clicked on parks in the map. Any ideas?

**Comment by 47ronin** [comment]
@enigma2522 ah, got it. Thanks! Okay, will try to chunk these so that the front-end framework stays intact. Just FYI if anything other than tabular data is output as `<table>` cells, I'll probably be converting them to `<div>` to keep it clean :grin:

**Comment by enigma2522** [comment]
Agreed. Just give me a heads up when you got things the way you want the and I'll work on pushing in the next round. Also, Are you planning on setting up a gh-pages branch? It sounded like you could publish the page directly on github by doing this... maybe? I am new to github, this may not be the case.

**Pull request merged**
